# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

apt_packages:
  - libxml2-dev

r_build_args: --no-build-vignettes
r_check_args: --no-build_vignettes --no-vignettes

env:
  global:
    - R_PKG="$(basename $TRAVIS_REPO_SLUG)"

deploy:
  provider: releases
  api_key:
    secure: ExoA0kJaw+U9skSHGhNF0KI8JpjfkfU7Ai61ILxgOUfpVQlGRjCqqT9gDzKfbNT/pBtoKZfL4ZfwnH+agULbJ9lr07YR0XKzG92nv0GNV/WhqX/NZxNvGowaEp5pmVegFJisnSPvuuiQekLta1KxvGoNkNHP87PZdDnEA8wmLdgHxJfM2Vc4s/yChcjKmaDnuGS6JhUgrxZwmUZEUgCB14ogibogvwQyWmsOkPxZgczsC75R0iUoe5tCQR44NxEvYQOopvAsqPuAcdBamnRVjK6NEhV6SJjf6axGDu4mjXs/t/dTLCJnJbA2WNSX5eyXiq8eTu5E0Isq8cSBPOAW6SunDO9TkPnR1DW+XIroS/TwjQp3UjfK8DDxOGdlV6Az8JElDZPcvGwR0LYowjuhNLo3ept+PQJYZRlE7fGikkjiI2ZlLrior/D+Lhhp5sQLxM9OgvcjQxA/crXZbjwxmNzrSDxmT8+gcOJNxh4BfqaXQflRNJkuvS4jovVEh9U/LjRF+vUSaw6EAbMK+8jeDVv3+CVu3B8LIroM09GKp7YV8776MBxyP6Dk7XKcOMnm2M1r99LKYB+UFEJX8VpFnTVxAfMAYmaWEQqJmZkm1+vDs6VXFfk00mIP1qme4byb0GOXV6VKtvZ3iGz7M5TMv+M8m/FPVdmw6vJz0Bp/tIs=
  file_glob: true
  file: ! "${R_PKG}_*.tar.gz"
  cleanup: true
  on:
    repo: KTH-Library/bibliomatrix
    tags: true
