# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
cache: packages

apt_packages:
- libxml2-dev
- libsodium-dev

r_build_args: "--no-build-vignettes"
r_check_args: "--no-build-vignettes --no-vignettes"

env:
  global:
  - R_PKG="$(basename $TRAVIS_REPO_SLUG)"
  
deploy:
  provider: releases
  api_key:
    secure: cDnXQDXxH6so7GjV6ERX/DgISek/JcT9witFe+IZ7MWURUdCjypbW39yqfpjvlIPfSwQ9KAoFzsPOfM90AiwjCCW5o05HoTR1TSgP8NmxjVd9rRJiRgzQDABFr2ago8vabxlAJwhFamej/nPGLql+QjeIwLBCuQiVxM9ayX/c3+XQ8+vapRC0KX9FuppnE12rCnxONlVb8ai9h2AbOfht4uIjWGg4zGB+OrdEP8c/YlpArS8lC2OMhDlgX6hbpGYKE2nMkOj1AXi83kVDo1WEGYJgy8XPTPL82p8/jgtdFDdVjGpEUKcw39VsZvtkCuZGzi3cKOzT5Caen83/AtuFWkbC+ol7DXF9ypZrRBYcU3W+bYnwvmOQmk/qMg1XrjvTlh5QTwadreUnMETXCJjzfyyTkVI+X5GGROEMqeBAY2kRq04b6PxoDemdNPEbDfuFLLC0uLV53LbqV9SFNp6NfNjLvghOU70li8bQ7wxUIXKeaye/5eOy7DwLuQPqEHd4YxutlxEfu49+8j54FL2n8M2SefRDhy46aBD7JOS9sLp0bj8wF8/F4YcIWwQaWENcSjApEIJyTRQvZ9RjfYr5A4s0ConSm/lFscAl5ZA9c72aas1F4C6ioJjF84NFR6iQuFVBjUaspQBzC38wFE91SVnXh2+07vkPigLGTX5U+M=
  file_glob: true
  file: ! "${R_PKG}_*.tar.gz"
  skip_cleanup: true
  overwrite: true
  on:
    repo: KTH-Library/bibliomatrix
    tags: true