#!/bin/bash
curl -o index.html http://localhost:8080/ui/divisions
mkdir -p division/na && curl -o division/na/index.html http://localhost:8080/ui/division/na
mkdir -p division/j && curl -o division/j/index.html -L -s http://localhost:8080/ui/division/j
mkdir -p division/s && curl -o division/s/index.html -L -s http://localhost:8080/ui/division/s
mkdir -p division/c && curl -o division/c/index.html -L -s http://localhost:8080/ui/division/c
mkdir -p division/m && curl -o division/m/index.html -L -s http://localhost:8080/ui/division/m
mkdir -p division/a && curl -o division/a/index.html -L -s http://localhost:8080/ui/division/a
mkdir -p division/j_jj && curl -o division/j_jj/index.html -L -s http://localhost:8080/ui/division/j%2Fjj
mkdir -p division/j_jr && curl -o division/j_jr/index.html -L -s http://localhost:8080/ui/division/j%2Fjr
mkdir -p division/s_sh && curl -o division/s_sh/index.html -L -s http://localhost:8080/ui/division/s%2Fsh
mkdir -p division/j_jh && curl -o division/j_jh/index.html -L -s http://localhost:8080/ui/division/j%2Fjh
mkdir -p division/s_sk && curl -o division/s_sk/index.html -L -s http://localhost:8080/ui/division/s%2Fsk
mkdir -p division/s_sm && curl -o division/s_sm/index.html -L -s http://localhost:8080/ui/division/s%2Fsm
mkdir -p division/m_mv && curl -o division/m_mv/index.html -L -s http://localhost:8080/ui/division/m%2Fmv
mkdir -p division/c_cg && curl -o division/c_cg/index.html -L -s http://localhost:8080/ui/division/c%2Fcg
mkdir -p division/s_sh_shg && curl -o division/s_sh_shg/index.html -L -s http://localhost:8080/ui/division/s%2Fsh%2Fshg
mkdir -p division/c_ce && curl -o division/c_ce/index.html -L -s http://localhost:8080/ui/division/c%2Fce
mkdir -p division/j_jr_jrl && curl -o division/j_jr_jrl/index.html -L -s http://localhost:8080/ui/division/j%2Fjr%2Fjrl
mkdir -p division/a_af && curl -o division/a_af/index.html -L -s http://localhost:8080/ui/division/a%2Faf
mkdir -p division/s_sm_smb && curl -o division/s_sm_smb/index.html -L -s http://localhost:8080/ui/division/s%2Fsm%2Fsmb
mkdir -p division/c_cj && curl -o division/c_cj/index.html -L -s http://localhost:8080/ui/division/c%2Fcj
mkdir -p division/a_al && curl -o division/a_al/index.html -L -s http://localhost:8080/ui/division/a%2Fal
mkdir -p division/j_jj_jjg && curl -o division/j_jj_jjg/index.html -L -s http://localhost:8080/ui/division/j%2Fjj%2Fjjg
mkdir -p division/c_cd && curl -o division/c_cd/index.html -L -s http://localhost:8080/ui/division/c%2Fcd
mkdir -p division/s_sf && curl -o division/s_sf/index.html -L -s http://localhost:8080/ui/division/s%2Fsf
mkdir -p division/m_mje && curl -o division/m_mje/index.html -L -s http://localhost:8080/ui/division/m%2Fmje
mkdir -p division/s_sm_sma && curl -o division/s_sm_sma/index.html -L -s http://localhost:8080/ui/division/s%2Fsm%2Fsma
mkdir -p division/j_jr_jro && curl -o division/j_jr_jro/index.html -L -s http://localhost:8080/ui/division/j%2Fjr%2Fjro
mkdir -p division/j_jj_jji && curl -o division/j_jj_jji/index.html -L -s http://localhost:8080/ui/division/j%2Fjj%2Fjji
mkdir -p division/j_jj_jjd && curl -o division/j_jj_jjd/index.html -L -s http://localhost:8080/ui/division/j%2Fjj%2Fjjd
mkdir -p division/m_mv_mvf && curl -o division/m_mv_mvf/index.html -L -s http://localhost:8080/ui/division/m%2Fmv%2Fmvf
mkdir -p division/m_mf && curl -o division/m_mf/index.html -L -s http://localhost:8080/ui/division/m%2Fmf
mkdir -p division/j_jj_jjn && curl -o division/j_jj_jjn/index.html -L -s http://localhost:8080/ui/division/j%2Fjj%2Fjjn
mkdir -p division/j_jj_jje && curl -o division/j_jj_jje/index.html -L -s http://localhost:8080/ui/division/j%2Fjj%2Fjje
mkdir -p division/j_jh_jhs && curl -o division/j_jh_jhs/index.html -L -s http://localhost:8080/ui/division/j%2Fjh%2Fjhs
mkdir -p division/a_ak && curl -o division/a_ak/index.html -L -s http://localhost:8080/ui/division/a%2Fak
mkdir -p division/j_jm && curl -o division/j_jm/index.html -L -s http://localhost:8080/ui/division/j%2Fjm
mkdir -p division/j_jm_jma && curl -o division/j_jm_jma/index.html -L -s http://localhost:8080/ui/division/j%2Fjm%2Fjma
mkdir -p division/m_mv_mvd && curl -o division/m_mv_mvd/index.html -L -s http://localhost:8080/ui/division/m%2Fmv%2Fmvd
mkdir -p division/s_sk_skr && curl -o division/s_sk_skr/index.html -L -s http://localhost:8080/ui/division/s%2Fsk%2Fskr
mkdir -p division/j_jh_jhk && curl -o division/j_jh_jhk/index.html -L -s http://localhost:8080/ui/division/j%2Fjh%2Fjhk
mkdir -p division/a_ag && curl -o division/a_ag/index.html -L -s http://localhost:8080/ui/division/a%2Fag
mkdir -p division/a_ak_akc && curl -o division/a_ak_akc/index.html -L -s http://localhost:8080/ui/division/a%2Fak%2Fakc
mkdir -p division/c_cl && curl -o division/c_cl/index.html -L -s http://localhost:8080/ui/division/c%2Fcl
mkdir -p division/c_cl_cla && curl -o division/c_cl_cla/index.html -L -s http://localhost:8080/ui/division/c%2Fcl%2Fcla
mkdir -p division/m_mg && curl -o division/m_mg/index.html -L -s http://localhost:8080/ui/division/m%2Fmg
mkdir -p division/c_cf && curl -o division/c_cf/index.html -L -s http://localhost:8080/ui/division/c%2Fcf
mkdir -p division/m_me && curl -o division/m_me/index.html -L -s http://localhost:8080/ui/division/m%2Fme
mkdir -p division/j_jr_jrr && curl -o division/j_jr_jrr/index.html -L -s http://localhost:8080/ui/division/j%2Fjr%2Fjrr
mkdir -p division/a_ai && curl -o division/a_ai/index.html -L -s http://localhost:8080/ui/division/a%2Fai
mkdir -p division/s_sk_skq && curl -o division/s_sk_skq/index.html -L -s http://localhost:8080/ui/division/s%2Fsk%2Fskq
mkdir -p division/j_jh_jhp && curl -o division/j_jh_jhp/index.html -L -s http://localhost:8080/ui/division/j%2Fjh%2Fjhp
mkdir -p division/m_mo && curl -o division/m_mo/index.html -L -s http://localhost:8080/ui/division/m%2Fmo
mkdir -p division/m_mje_mjeb && curl -o division/m_mje_mjeb/index.html -L -s http://localhost:8080/ui/division/m%2Fmje%2Fmjeb
mkdir -p division/c_ce_cee && curl -o division/c_ce_cee/index.html -L -s http://localhost:8080/ui/division/c%2Fce%2Fcee
mkdir -p division/c_ce_ced && curl -o division/c_ce_ced/index.html -L -s http://localhost:8080/ui/division/c%2Fce%2Fced
mkdir -p division/m_mv_mve && curl -o division/m_mv_mve/index.html -L -s http://localhost:8080/ui/division/m%2Fmv%2Fmve
mkdir -p division/c_ce_cef && curl -o division/c_ce_cef/index.html -L -s http://localhost:8080/ui/division/c%2Fce%2Fcef
mkdir -p division/s_sm_smb_smbe && curl -o division/s_sm_smb_smbe/index.html -L -s http://localhost:8080/ui/division/s%2Fsm%2Fsmb%2Fsmbe
mkdir -p division/j_jr_jrq && curl -o division/j_jr_jrq/index.html -L -s http://localhost:8080/ui/division/j%2Fjr%2Fjrq
mkdir -p division/j_jh_jht && curl -o division/j_jh_jht/index.html -L -s http://localhost:8080/ui/division/j%2Fjh%2Fjht
mkdir -p division/s_sf_sfb && curl -o division/s_sf_sfb/index.html -L -s http://localhost:8080/ui/division/s%2Fsf%2Fsfb
mkdir -p division/j_jr_jrt && curl -o division/j_jr_jrt/index.html -L -s http://localhost:8080/ui/division/j%2Fjr%2Fjrt
mkdir -p division/c_cj_cjd && curl -o division/c_cj_cjd/index.html -L -s http://localhost:8080/ui/division/c%2Fcj%2Fcjd
mkdir -p division/m_mo_mob && curl -o division/m_mo_mob/index.html -L -s http://localhost:8080/ui/division/m%2Fmo%2Fmob
mkdir -p division/s_sm_smb_smba && curl -o division/s_sm_smb_smba/index.html -L -s http://localhost:8080/ui/division/s%2Fsm%2Fsmb%2Fsmba
mkdir -p division/a_ag_agb && curl -o division/a_ag_agb/index.html -L -s http://localhost:8080/ui/division/a%2Fag%2Fagb
mkdir -p division/a_ad && curl -o division/a_ad/index.html -L -s http://localhost:8080/ui/division/a%2Fad
mkdir -p division/m_mg_mgn && curl -o division/m_mg_mgn/index.html -L -s http://localhost:8080/ui/division/m%2Fmg%2Fmgn
mkdir -p division/s_sk_ski && curl -o division/s_sk_ski/index.html -L -s http://localhost:8080/ui/division/s%2Fsk%2Fski
mkdir -p division/m_mje_mjec && curl -o division/m_mje_mjec/index.html -L -s http://localhost:8080/ui/division/m%2Fmje%2Fmjec
mkdir -p division/s_sk_ske && curl -o division/s_sk_ske/index.html -L -s http://localhost:8080/ui/division/s%2Fsk%2Fske
mkdir -p division/c_cg_cgf && curl -o division/c_cg_cgf/index.html -L -s http://localhost:8080/ui/division/c%2Fcg%2Fcgf
mkdir -p division/s_sm_sma_smac && curl -o division/s_sm_sma_smac/index.html -L -s http://localhost:8080/ui/division/s%2Fsm%2Fsma%2Fsmac
mkdir -p division/c_cg_cgh && curl -o division/c_cg_cgh/index.html -L -s http://localhost:8080/ui/division/c%2Fcg%2Fcgh
mkdir -p division/m_me_mez && curl -o division/m_me_mez/index.html -L -s http://localhost:8080/ui/division/m%2Fme%2Fmez
mkdir -p division/a_al_ali && curl -o division/a_al_ali/index.html -L -s http://localhost:8080/ui/division/a%2Fal%2Fali
mkdir -p division/a_al_alg && curl -o division/a_al_alg/index.html -L -s http://localhost:8080/ui/division/a%2Fal%2Falg
mkdir -p division/s_sk_skd && curl -o division/s_sk_skd/index.html -L -s http://localhost:8080/ui/division/s%2Fsk%2Fskd
mkdir -p division/c_cg_cgd && curl -o division/c_cg_cgd/index.html -L -s http://localhost:8080/ui/division/c%2Fcg%2Fcgd
mkdir -p division/m_mf_mfc && curl -o division/m_mf_mfc/index.html -L -s http://localhost:8080/ui/division/m%2Fmf%2Fmfc
mkdir -p division/c_cg_cge && curl -o division/c_cg_cge/index.html -L -s http://localhost:8080/ui/division/c%2Fcg%2Fcge
mkdir -p division/s_sm_sma_smaa && curl -o division/s_sm_sma_smaa/index.html -L -s http://localhost:8080/ui/division/s%2Fsm%2Fsma%2Fsmaa
mkdir -p division/c_cg_cgi && curl -o division/c_cg_cgi/index.html -L -s http://localhost:8080/ui/division/c%2Fcg%2Fcgi
mkdir -p division/s_sh_shh && curl -o division/s_sh_shh/index.html -L -s http://localhost:8080/ui/division/s%2Fsh%2Fshh
mkdir -p division/j_jh_jhf && curl -o division/j_jh_jhf/index.html -L -s http://localhost:8080/ui/division/j%2Fjh%2Fjhf
mkdir -p division/c_ch && curl -o division/c_ch/index.html -L -s http://localhost:8080/ui/division/c%2Fch
mkdir -p division/c_ch_chd && curl -o division/c_ch_chd/index.html -L -s http://localhost:8080/ui/division/c%2Fch%2Fchd
mkdir -p division/a_af_aff && curl -o division/a_af_aff/index.html -L -s http://localhost:8080/ui/division/a%2Faf%2Faff
mkdir -p division/c_ce_ceg && curl -o division/c_ce_ceg/index.html -L -s http://localhost:8080/ui/division/c%2Fce%2Fceg
mkdir -p division/a_af_afe && curl -o division/a_af_afe/index.html -L -s http://localhost:8080/ui/division/a%2Faf%2Fafe
mkdir -p division/s_sm_sma_smab && curl -o division/s_sm_sma_smab/index.html -L -s http://localhost:8080/ui/division/s%2Fsm%2Fsma%2Fsmab
mkdir -p division/a_al_alk && curl -o division/a_al_alk/index.html -L -s http://localhost:8080/ui/division/a%2Fal%2Falk
mkdir -p division/a_af_afp && curl -o division/a_af_afp/index.html -L -s http://localhost:8080/ui/division/a%2Faf%2Fafp
mkdir -p division/m_mf_mfe && curl -o division/m_mf_mfe/index.html -L -s http://localhost:8080/ui/division/m%2Fmf%2Fmfe
mkdir -p division/a_al_alh && curl -o division/a_al_alh/index.html -L -s http://localhost:8080/ui/division/a%2Fal%2Falh
mkdir -p division/c_cg_cgg && curl -o division/c_cg_cgg/index.html -L -s http://localhost:8080/ui/division/c%2Fcg%2Fcgg
mkdir -p division/c_cd_cdd && curl -o division/c_cd_cdd/index.html -L -s http://localhost:8080/ui/division/c%2Fcd%2Fcdd
mkdir -p division/c_cj_cjh && curl -o division/c_cj_cjh/index.html -L -s http://localhost:8080/ui/division/c%2Fcj%2Fcjh
mkdir -p division/m_ml && curl -o division/m_ml/index.html -L -s http://localhost:8080/ui/division/m%2Fml
mkdir -p division/c_cj_cje && curl -o division/c_cj_cje/index.html -L -s http://localhost:8080/ui/division/c%2Fcj%2Fcje
mkdir -p division/c_cj_cjf && curl -o division/c_cj_cjf/index.html -L -s http://localhost:8080/ui/division/c%2Fcj%2Fcjf
mkdir -p division/c_cd_cdi && curl -o division/c_cd_cdi/index.html -L -s http://localhost:8080/ui/division/c%2Fcd%2Fcdi
mkdir -p division/a_af_afh && curl -o division/a_af_afh/index.html -L -s http://localhost:8080/ui/division/a%2Faf%2Fafh
mkdir -p division/c_cd_cdg && curl -o division/c_cd_cdg/index.html -L -s http://localhost:8080/ui/division/c%2Fcd%2Fcdg
mkdir -p division/s_sm_smb_smbd && curl -o division/s_sm_smb_smbd/index.html -L -s http://localhost:8080/ui/division/s%2Fsm%2Fsmb%2Fsmbd
mkdir -p division/a_ai_aib && curl -o division/a_ai_aib/index.html -L -s http://localhost:8080/ui/division/a%2Fai%2Faib
mkdir -p division/s_sm_smb_smbc && curl -o division/s_sm_smb_smbc/index.html -L -s http://localhost:8080/ui/division/s%2Fsm%2Fsmb%2Fsmbc
mkdir -p division/s_sk_skf && curl -o division/s_sk_skf/index.html -L -s http://localhost:8080/ui/division/s%2Fsk%2Fskf
mkdir -p division/c_ck && curl -o division/c_ck/index.html -L -s http://localhost:8080/ui/division/c%2Fck
mkdir -p division/c_ck_cka && curl -o division/c_ck_cka/index.html -L -s http://localhost:8080/ui/division/c%2Fck%2Fcka
mkdir -p division/s_sm_smb_smbb && curl -o division/s_sm_smb_smbb/index.html -L -s http://localhost:8080/ui/division/s%2Fsm%2Fsmb%2Fsmbb
mkdir -p division/a_af_aft && curl -o division/a_af_aft/index.html -L -s http://localhost:8080/ui/division/a%2Faf%2Faft
mkdir -p division/s_sf_sfd && curl -o division/s_sf_sfd/index.html -L -s http://localhost:8080/ui/division/s%2Fsf%2Fsfd
mkdir -p division/m_mje_mjem && curl -o division/m_mje_mjem/index.html -L -s http://localhost:8080/ui/division/m%2Fmje%2Fmjem
mkdir -p division/s_sh_shd && curl -o division/s_sh_shd/index.html -L -s http://localhost:8080/ui/division/s%2Fsh%2Fshd
mkdir -p division/c_cf_cfg && curl -o division/c_cf_cfg/index.html -L -s http://localhost:8080/ui/division/c%2Fcf%2Fcfg
mkdir -p division/c_cj_cjg && curl -o division/c_cj_cjg/index.html -L -s http://localhost:8080/ui/division/c%2Fcj%2Fcjg
mkdir -p division/s_sh_sho && curl -o division/s_sh_sho/index.html -L -s http://localhost:8080/ui/division/s%2Fsh%2Fsho
mkdir -p division/a_ad_ade && curl -o division/a_ad_ade/index.html -L -s http://localhost:8080/ui/division/a%2Fad%2Fade
mkdir -p division/s_sh_she && curl -o division/s_sh_she/index.html -L -s http://localhost:8080/ui/division/s%2Fsh%2Fshe
mkdir -p division/m_me_mey && curl -o division/m_me_mey/index.html -L -s http://localhost:8080/ui/division/m%2Fme%2Fmey
mkdir -p division/m_mf_mfg && curl -o division/m_mf_mfg/index.html -L -s http://localhost:8080/ui/division/m%2Fmf%2Fmfg
mkdir -p division/a_af_afb && curl -o division/a_af_afb/index.html -L -s http://localhost:8080/ui/division/a%2Faf%2Fafb
mkdir -p division/j_jr_jrc && curl -o division/j_jr_jrc/index.html -L -s http://localhost:8080/ui/division/j%2Fjr%2Fjrc
mkdir -p division/a_ad_adc && curl -o division/a_ad_adc/index.html -L -s http://localhost:8080/ui/division/a%2Fad%2Fadc
mkdir -p division/c_cf_cfj && curl -o division/c_cf_cfj/index.html -L -s http://localhost:8080/ui/division/c%2Fcf%2Fcfj
mkdir -p division/c_cd_cdh && curl -o division/c_cd_cdh/index.html -L -s http://localhost:8080/ui/division/c%2Fcd%2Fcdh
mkdir -p division/c_cj_cjc && curl -o division/c_cj_cjc/index.html -L -s http://localhost:8080/ui/division/c%2Fcj%2Fcjc
mkdir -p division/a_ag_agf && curl -o division/a_ag_agf/index.html -L -s http://localhost:8080/ui/division/a%2Fag%2Fagf
mkdir -p division/m_mg_mgh && curl -o division/m_mg_mgh/index.html -L -s http://localhost:8080/ui/division/m%2Fmg%2Fmgh
mkdir -p division/s_sf_sfe && curl -o division/s_sf_sfe/index.html -L -s http://localhost:8080/ui/division/s%2Fsf%2Fsfe
mkdir -p division/c_cf_cff && curl -o division/c_cf_cff/index.html -L -s http://localhost:8080/ui/division/c%2Fcf%2Fcff
mkdir -p division/a_ai_aie && curl -o division/a_ai_aie/index.html -L -s http://localhost:8080/ui/division/a%2Fai%2Faie
mkdir -p division/m_me_mew && curl -o division/m_me_mew/index.html -L -s http://localhost:8080/ui/division/m%2Fme%2Fmew
mkdir -p division/s_sf_sfc && curl -o division/s_sf_sfc/index.html -L -s http://localhost:8080/ui/division/s%2Fsf%2Fsfc
mkdir -p division/m_ml_mlf && curl -o division/m_ml_mlf/index.html -L -s http://localhost:8080/ui/division/m%2Fml%2Fmlf
mkdir -p division/m_ml_mle && curl -o division/m_ml_mle/index.html -L -s http://localhost:8080/ui/division/m%2Fml%2Fmle
mkdir -p division/a_ak_akb && curl -o division/a_ak_akb/index.html -L -s http://localhost:8080/ui/division/a%2Fak%2Fakb
mkdir -p division/a_ai_aic && curl -o division/a_ai_aic/index.html -L -s http://localhost:8080/ui/division/a%2Fai%2Faic
mkdir -p division/c_cg_cgk && curl -o division/c_cg_cgk/index.html -L -s http://localhost:8080/ui/division/c%2Fcg%2Fcgk
mkdir -p division/s_sk_skk && curl -o division/s_sk_skk/index.html -L -s http://localhost:8080/ui/division/s%2Fsk%2Fskk
mkdir -p division/m_mg_mgi && curl -o division/m_mg_mgi/index.html -L -s http://localhost:8080/ui/division/m%2Fmg%2Fmgi
mkdir -p division/s_sk_sko && curl -o division/s_sk_sko/index.html -L -s http://localhost:8080/ui/division/s%2Fsk%2Fsko
mkdir -p division/a_ag_agi && curl -o division/a_ag_agi/index.html -L -s http://localhost:8080/ui/division/a%2Fag%2Fagi
mkdir -p division/a_ai_aid && curl -o division/a_ai_aid/index.html -L -s http://localhost:8080/ui/division/a%2Fai%2Faid
mkdir -p division/c_cf_cfd && curl -o division/c_cf_cfd/index.html -L -s http://localhost:8080/ui/division/c%2Fcf%2Fcfd
mkdir -p division/m_mo_mod && curl -o division/m_mo_mod/index.html -L -s http://localhost:8080/ui/division/m%2Fmo%2Fmod
mkdir -p division/s_sf_sfw && curl -o division/s_sf_sfw/index.html -L -s http://localhost:8080/ui/division/s%2Fsf%2Fsfw
mkdir -p division/m_mf_mfyb && curl -o division/m_mf_mfyb/index.html -L -s http://localhost:8080/ui/division/m%2Fmf%2Fmfyb
mkdir -p division/a_ad_adb && curl -o division/a_ad_adb/index.html -L -s http://localhost:8080/ui/division/a%2Fad%2Fadb
mkdir -p division/m_mo_moe && curl -o division/m_mo_moe/index.html -L -s http://localhost:8080/ui/division/m%2Fmo%2Fmoe
mkdir -p division/c_cd_cdf && curl -o division/c_cd_cdf/index.html -L -s http://localhost:8080/ui/division/c%2Fcd%2Fcdf
mkdir -p division/m_mf_mfd && curl -o division/m_mf_mfd/index.html -L -s http://localhost:8080/ui/division/m%2Fmf%2Fmfd
mkdir -p division/m_mf_mfg_mfgg && curl -o division/m_mf_mfg_mfgg/index.html -L -s http://localhost:8080/ui/division/m%2Fmf%2Fmfg%2Fmfgg
mkdir -p division/c_cd_cdj && curl -o division/c_cd_cdj/index.html -L -s http://localhost:8080/ui/division/c%2Fcd%2Fcdj
mkdir -p division/c_cj_cji && curl -o division/c_cj_cji/index.html -L -s http://localhost:8080/ui/division/c%2Fcj%2Fcji
