---
title: "ABM - staffbased"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    favicon: kth-logo.png
    fig_mobile: FALSE
params:
  unit_code: !r bibliomatrix:::abm_config()$default_unit
  is_employee: FALSE
  use_package_data: TRUE
  embed_data: FALSE
---
  
  
```{r setup, include=FALSE}
# unit slug for testing:

# "j/jh/jhs"
# 

library(flexdashboard)
library(DT)
library(readr)
library(purrr)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(bibliomatrix)
library(tidyr)
library(scales)
#library(plotly)
library(kableExtra)
library(glue)
library(extrafont)

colors_vb <- palette_kth(4)

# Retrieve result tables to use in tabs and key indicators

# Dummy org data
unit_code<- "j/jh/jhs"
unit_members<- unit_staff(unit_slug=unit_code)
unit_publ<- abm_staff_data(kthids=unit_members$kthid)


#if (params$use_package_data != TRUE) {
  con <- pool_bib()
  df_diva <- abm_table1_alt(con = con, data=unit_publ) 
  df_cit3y <- abm_table2_alt(con = con, data=unit_publ)
#  df_cf <- abm_table3(con = con, unit_code= params$unit_code)
#  df_jcf <- abm_table4(con = con, unit_code= params$unit_code)
#  df_copub <- abm_table5(con = con, unit_code= params$unit_code)
#  df_woscov <- abm_woscoverage(con = con, unit_code = params$unit_code)
#  df_oa <- abm_table6(con = con, unit_code = params$unit_code)
#  unit_meta <- unit_info(con = con) %>% filter(unit_code == params$unit_code)
  pool::poolClose(con)
#} else {
#  df_diva <- pluck(abm_public_kth$units, params$unit_code, 1)
#  df_cit3y <- pluck(abm_public_kth$units, params$unit_code, 2)
#  df_cf <- pluck(abm_public_kth$units, params$unit_code, 3)
#  df_jcf <- pluck(abm_public_kth$units, params$unit_code, 4)
#  df_copub <- pluck(abm_public_kth$units, params$unit_code, 5)
#  df_oa <- pluck(abm_public_kth$units, params$unit_code, "oa")
#  df_woscov <- pluck(abm_public_kth$units, params$unit_code, "coverage")
#  unit_meta <- filter(abm_public_kth$meta, unit_code == params$unit_code)
#}

#unit_level <- abm_public_kth$meta %>% 
#  filter(unit_code == params$unit_code) %>%
#  pull(org_level)

#if(isTRUE(unit_level >= 0)){
#  
#  unit_label <- 
#    abm_public_kth$meta %>% 
#    filter(unit_code == params$unit_code) %>%
#    pull(unit_long_en)
#  
#} else {
  
#  unit_label <- 
#    ad_displayname2(kthid = params$unit_code)
#}

#unit_label <- paste0("Annual Bibliometric Monitoring: ", unit_label)
unit_label <- unit_code
unit_file_label<- "Test"
abm_unit_title<- "Test"



current_date <- format(Sys.Date(), "%Y%m%d")

#abm_unit_title<- paste0("ABM: ",unit_label)

```

Publications in DiVA
=====================================
  
#### `r unit_label`
  
Row
---------------------
  
### **Publication volume, fractionalized** {.no-padding .no-mobile}
  
<!-- <div style='width:720px;margin:auto'> -->
  
<style type="text/css">
div.dt-buttons {
  position:relative;
  float:right;
}
</style>
  
```{r, fig.width=3.75}

abm_ui_datatable_diva(
  df_diva, 
  unit_file_label = unit_file_label, 
  unit_title = abm_unit_title
)

```
<!-- </div> -->
  
### **Publication volume, fractionalized** {.no-padding .mobile}
  
```{r, fig.width=3.75}
abm_ui_kable_diva(df_diva)
```


Row
---------------------
  
### **Publication volume** {.no-padding .no-mobile}
  
```{r, fig.width=8, fig.height=5}
if (nrow(df_diva) > 0) {
  p <- abm_graph_diva(df_diva)
  p
} else {
  shiny::HTML("<p><i>There are no publications available for this graph</i></p>")
}
```

### **Publication volume** {.no-padding .mobile}

```{r, fig.width=8, fig.height = 5}
if (nrow(df_diva) > 0) {
  p
} else {
  shiny::HTML("<p><i>There are no publications available for this graph</i></p>")
}
``` 

### **Web of Science coverage by publication type** {.no-padding .no-mobile}

```{r, fig.width=3, fig.height=5}
if (nrow(df_diva) > 0) {
  p <- abm_graph_wos_coverage(df_diva)
  p
} else {
  shiny::HTML("<p><i>There are no publications available for this graph</i></p>")
}
```

### **Web of Science coverage by publication type** {.no-padding .mobile}

```{r, fig.width=3, fig.height=5}
if (nrow(df_diva) > 0) {
  p
} else {
  shiny::HTML("<p><i>There are no publications available for this graph</i></p>")
}
```

Blank
=====================================
